---
- name: Playbook
  hosts: localhost
  gather_facts: no
  connection: local
  become: True

  tasks:
    - name: "Install required packages"
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "build-essential"
        - "python3-dev"

    # we need to download and install manually the lib because the pypi package is not up to date.
    # see https://github.com/adafruit/Adafruit_Python_DHT/issues/77
    - name: "install Adafruit_dht for dependence"
      shell: "sudo pip3 Adafruit_dht"

    - name: "Install Adafruit python lib"
      shell: "sudo python3 setup.py install"
      args:
        chdir: "/tmp/Adafruit_Python_DHT"
